apiVersion: apps/v1 # we need to have a API version
kind: Deployment # only certain set allowed (Service,Job)
metadata: # you can add lot of metadata for your deployment
  name: volume-app-deployment # this is your deployment name
spec: # config of deployment
  replicas: 3 # number of pods you want
  selector:
    matchLabels: # list down labels you want to control
      app: volume-app

  template: # this is your image for deployment
    metadata:
      labels: # you can add one or more labels
        app: volume-app # any key-value pair
    spec: # config of pod
      containers:
        - name: volume-node
          image: harshvardhan33/docker-kub-vol
          volumeMounts:
            - mountPath: /app/datafolder
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: host-pvc
          # emptyDir: {} # container restarts survives but does not pod / only relevant for single pod 
          # hostPath: # shares path between multiple pods
          #  path: /data
          #  type: DirectoryOrCreate
