apiVersion: v1
kind: Service
metadata:
  name: volume-service 
spec:
  selector:
    app: volume-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 5000
  # ClusterIP - internally to cluster 
  # NodePort - only locally 
  type: LoadBalancer